version: 2.1
orbs:
  maven: circleci/maven@1.1
commands: # a reusable command with parameters
  hello-function:
    parameters:
      to:
        default: "India"
        type: string
    steps:
      - run: echo "Hello from <<parameters.to>>"
jobs:
  my-job:
    docker:
      - image: cimg/base:stable     
    steps:
      - hello-function:
          to: "India"
  
  test2:
    working_directory: ~/test
    environment:
      NODE_ENV: "circle"
    docker:
      - image: circleci/node:10.16.3-stretch
    steps:
      - checkout
      - run:
          command: ls -ltrh
      - run:
          command: dir 
      - run:
          command: |
            chmod 777 .circleci/hello.sh
            .circleci/hello.sh
  
workflows:
  my-workflow:
    jobs:
     - my-job
     - test2
  maven-test:
    jobs:
      - maven/test
    
