version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
commands: # a reusable command with parameters
  hello-function:
    parameters:
      to:
        default: "India"
        type: string
    steps:
      - run: echo "Hello from <<parameters.to>>"
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
       
    steps:
      - hello-function:
          to: "India"
workflows:
  my-workflow:
    jobs:
      - my-job