# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  test1:
    working_directory: ~/test
    environment:
      NODE_ENV: "circle"
    docker:
      - image: circleci/node:10.16.3-stretch
    steps:
      - checkout
      - run:
          command: ls -ltrh
      - run:
          command: dir 
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
     # - welcome/run
      - test1
