version: 2.1
orbs:
  maven: circleci/maven@1.1
commands: # a reusable command with parameters
  hello-function:
    parameters:
      to:
        default: "India"
        type: string
    steps:
      - run: echo "Hello again from <<parameters.to>>"
jobs:
  build:
    docker:
      - image: python:3.6.3-jessie
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
  my-job:
    docker:
      - image: cimg/base:stable     
    steps:
      - hello-function:
          to: "India"
  
  test2:
    working_directory: ~/test
    environment:
      NODE_ENV: "circle"
    docker:
      - image: circleci/node:10.16.3-stretch
    steps:
      - checkout
      - run:
          command: ls -ltrh
      - run:
          command: dir 
      - run:
          command: |
            chmod 777 .circleci/hello.sh
            .circleci/hello.sh
  maven-test:
    working_directory: ~/test
    environment:
      NODE_ENV: "circle"
    docker:
      - image: cimg/openjdk:11.0
    steps:
      # Checkout the code as the first step.
      - checkout
      # Use mvn clean and package as the standard maven build phase
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn test
      - store_artifacts:
          path : /home/circleci/test/target/my-webapp.war
workflows:
  artifact-test:
    jobs:
      - build
  my-workflow:
    jobs:
     - my-job:
        type: approval
     - test2:
        requires:
          - my-job
  maven-test:
    jobs:
      - maven-test
    
